### PR TITLE
feat(deps): upgrade to new bpmn-js version

### PR DESCRIPTION
**Pull request by peterhnm**
**Description**
* Upgrade the version of:
    * bpmn-js
    * properties-panel
    * token simulation plugin

### CODE REVIEW

**Comment by peterhnm** [comment]
@Hafflgav you once said that because of the rounded corners we should upgrade the version of bpmn-js. That is why I requested a review from you.

**Comment by Hafflgav** [comment]
Thanks @peterhnm! 
I tried it out very quickly but ran into a problem. 

Apparently I am getting an error message in vs-code: 
image

In the console of the vs-code developer I can see this error: 
```
Error: Unable to read file 'c:\Users\...\miranum-vs-code-modeler\dist\client\style.css' (Error: Unable to resolve nonexistent file 'c:\Users\...\miranum-vs-code-modeler\dist\client\style.css')
    at l.w (fileService.ts:584:10)
    at l.v (fileService.ts:569:15)
    at async w (resourceLoading.ts:68:18)
    at async r.rb (webviewElement.ts:723:19)
resourceLoading.ts:82 Error: Unable to read file 'c:\Users\...\miranum-vs-code-modeler\dist\client\assets\bpmn-font\css\bpmn.css' (Error: Unable to resolve nonexistent file 'c:\Users\...e\miranum-vs-code-modeler\dist\client\assets\bpmn-font\css\bpmn.css')
    at l.w (fileService.ts:584:10)
    at l.v (fileService.ts:569:15)
    at async w (resourceLoading.ts:68:18)
    at async r.rb (webviewElement.ts:723:19)
```

I will try it out tomorrow properly and see if the problem persists. :)

**Comment by peterhnm** [comment]
Apparently a few files are missing. Maybe rebuilding the extension can solve this problem.

**Review by Hafflgav — APPROVED** [review]
You were right... Somehow I missed hitting the` npm run build` command on my personal machine. I thought by pressing `F5` everything is build right away. 🤦 

Works on my machine now and looks pretty awesome! 
Great work 🚀

**Pull request merged**
